
connection:
  host: 127.0.0.1
  port: 8080

web:
  host: http://localhost
  port: '3000'

jwt:
  secret: secret

mongo:
  host: 127.0.0.1
  port: 27017
  db: bfriedrichs

  user:
    username: admin
    password: password
