
connection:
  host: 127.0.0.1
  port: 8080
  webhost: http://localhost:9009

jwt:
  secret: secret

paths:
  root: .
  public: dist/public
  images: dist/images
  uploads: dist/uploads
  static: dist/static
  cache: dist/node_cache

mongo:
  host: 127.0.0.1
  port: 27017
  db: bfriedrichs

  user:
    username: admin
    password: password

dev: True
