
connection:
  host: 127.0.0.1
  port: 8080
  webhost: http://127.0.0.1:3000
  imagehost: http://127.0.0.1:8000

jwt:
  secret: secret

paths:
  root: .
  public: dist/public
  images: dist/images
  uploads: dist/uploads
  static: dist/static
  cache: dist/node_cache

mongo:
  host: 127.0.0.1
  port: 27017
  db: bfriedrichs

  user:
    username: admin
    password: password

node:
  address: 127.0.0.1
  port: 9009

dev: True
