
connection:
  host: 127.0.0.1
  port: 8080
  webhost: http://localhost:9009

jwt:
  secret: secret

paths:
  root: .

mongo:
  url: 127.0.0.1:27017
  db: bfriedrichs

  user:
    username: admin
    password: password

dev: True
