version: "3.9"
services:
  web:
    image: bjoernf
    expose:
      - 80
    environment:
      PORT: 80
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: web.bjoernf.com
      LETSENCRYPT_HOST: web.bjoernf.com
    networks:
      - nginx-proxy
    restart: unless-stopped
  analytics:
    image: electerious/ackee
    restart: unless-stopped
    expose:
      - 80
    environment:
      VIRTUAL_HOST: dashboard.bjoernf.com
      LETSENCRYPT_HOST: dashboard.bjoernf.com
      VIRTUAL_PORT: 80
      ACKEE_PORT: 80
      ACKEE_ALLOW_ORIGIN: https://bjoernf.com
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
