version: "3.9"
services:
  render-server:
    image: bjornf-render-server
    expose:
      - 9009
    networks:
      - default
    restart: unless-stopped
  api:
    image: bjornf-api
    restart: unless-stopped
    links:
      - mongo
      - render-server
    depends_on:
      - mongo
      - render-server
    environment:
      API_CONNECTION_HOST: 0.0.0.0
      API_CONNECTION_PORT: '8080'
      API_MONGO_HOST: mongo
      API_NODE_ADDRESS: render-server
    networks:
      - default
      - nginx-proxy
    volumes:
      - staticvolume:/api/blogapi/dist/public
      - uploadvolume:/api/blogapi/dist/uploads
  mongo:
    image: mongo
    restart: unless-stopped
    networks:
      - default
  static:
    image: bjornf-static
    volumes:
      - staticvolume:/usr/share/nginx/html
    networks:
      - nginx-proxy
  image-server:
    image: bjornf-image-server
    volumes:
      - uploadvolume:/dist/uploads
    networks:
      - nginx-proxy

volumes:
  staticvolume:
  uploadvolume:

networks:
  default:
    name: app-network
    driver: bridge
  nginx-proxy:
    external: true