version: "3.9"
services:
  api:
    restart: unless-stopped
    environment:
      API_CONNECTION_PORT: '8080'
    networks:
      - default


networks:
  default:
    name: app-network
    driver: bridge
