version: "3.9"
services:
  render-server:
    networks:
      - default
    restart: unless-stopped

  api:
    restart: unless-stopped
    links:
      - mongo
      - render-server
    depends_on:
      - mongo
    environment:

      API_CONNECTION_PORT: '8080'
      API_MONGO_HOST: mongo
    networks:
      - default
  mongo:
    image: mongo
    restart: unless-stopped
    networks:
      - default


networks:
  default:
    name: app-network
    driver: bridge
