version: "3.9"
services:
  web:
    build: ./web
    command: yarn run start
    expose:
      - 1234
    ports:
      - 1234:1234
    environment:
      REACT_APP_API_URL: http://localhost:8000
    volumes:
      - ./web/dist/:/web/dist
      - ./web/app:/web/app
  render-server:
    command: yarn node watch.js
    build: ./render-server
    depends_on:
      - api
    links:
      - api
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://api:8000
    expose:
      - 9009
    ports:
      - 9009:9009
    volumes:
      - ./web/dist/:/render-server/dist
  api:
    build: ./api
    command: adev runserver blogapi
    depends_on:
      - mongo
    links:
      - mongo
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./api/blogapi:/api/blogapi
    environment:
      API_CONNECTION_HOST: 0.0.0.0
      API_CONNECTION_PORT: '8000'
      API_MONGO_URL: mongodb://mongo:27017
  mongo:
    image: mongo
    restart: unless-stopped
    networks:
      - default


networks:
  default:
    driver: bridge