version: "3.9"
services:
  web:
    build: ./web
    command: yarn start
    expose:
      - 1234
      - 8080
    ports:
      - 1234:1234
      - 8080:8080
    environment:
      REACT_APP_API_URL: http://localhost:8000
    volumes:
      - ./web/dist/:/web/dist
      - ./web/app:/web/app
      - ./web/.docker-parcel-cache:/web/.parcel-cache
  render-server:
    command: yarn node watch.js
    build: ./render-server
    depends_on:
      - api
    links:
      - api
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://api:8000
    expose:
      - 9009
    ports:
      - 9009:9009
    volumes:
      - ./render-server:/render-server
      - ./web/dist/:/render-server/dist
    networks:
      - default
    restart: unless-stopped
  api:
    build: ./api
    command: adev runserver blogapi
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./api/blogapi:/api/blogapi
    environment:
      API_CONNECTION_HOST: 0.0.0.0
      API_CONNECTION_PORT: '8000'
      API_MONGO_URL: mongodb://host.docker.internal:27017


networks:
  default:
    driver: bridge